---
title: "TCGA Head and Neck Cancer Example analysis"
subtitle: "DNA methytion predicted proteins, tissue type, and cancer progression"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: Paul Yousefi
output:
  html_document:
    toc: true
    highlight: tango
---

```{r setoptions, eval = TRUE, echo = FALSE}
knitr::opts_chunk$set(
  comment = ">",
  error = FALSE,
  tidy = FALSE,
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  cache = FALSE
)
```

```{r call_source, echo = F}
library(here)
readRenviron(here("config.env"))

datadir <- Sys.getenv("datadir")
resultsdir <- Sys.getenv("resultsdir")

path <- here("scripts")
sourcecode <- grep("analysis.r$",
  list.files(path),
  value = T
)
read_chunk(file.path(path, sourcecode))
```

# Load cleaned TCGA clinical and predicted protein level data

```{r globals, results = 'hide'}
```

```{r load.data}
```

```{r names, results = 'hide'}
```

## Run glms for association between proteins levels and tissue type (tumor vs. normal)

```{r tissue}
```

### Visualize results

```{r tissue.figs}
```

## Run glms for association between proteins levels and progression free interval (PFI)

This analysis should be restricted to measurements taken from tumor samples

```{r pfi}
```

### Visualize results

```{r pfi.figs}
```
